import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import '@mantine/core/styles.css';
import '@mantine/charts/styles.css';
import '@mantine/dates/styles.css';
import '@mantine/dropzone/styles.css';
import '@mantine/notifications/styles.css';
import 'react-phone-input-2/lib/style.css';
import './globals.css';
import { MantineProvider } from '@mantine/core';
import { Notifications } from '@mantine/notifications';
import ReactQueryConfig from '@/src/config/react-query-config';
import { TokenProvider } from '@/src/hooks/use-token';
import { authDecodedToken } from '@/token';
import { NuqsAdapter } from 'nuqs/adapters/next/app';
import { Toaster } from '@/src/components/toast';
import { SelectRowTableProvider } from '@/src/components/select-row-table-context';
import { GoogleAuthProvider } from "@/src/services/google-auth";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const token = await authDecodedToken();
  const messages = (await import(`@/messages/${locale}.json`)).default;
  return (
    <html lang={locale} dir={locale === 'ar' ? 'rtl' : 'ltr'}>
      <body className="overflow-x-hidden relative">
        <div
          className="w-screen max-h-[150vh] h-full absolute top-0 left-0"
          style={{
            background:
              'linear-gradient(180deg, #F0F6FB 0%, #F0F6FB 35%,#EBF6EDBD 70%, #DFF5C608 88%, #DFF5C608 100%)',
          }}
        />
        <div className="relative">
          <GoogleAuthProvider>
            <TokenProvider value={token ? token : null}>
              <NuqsAdapter>
                <ReactQueryConfig>
                  <MantineProvider>
                    <NextIntlClientProvider locale={locale} messages={messages}>
                      <Notifications position="top-right" zIndex={2000} />
                      <SelectRowTableProvider>{children}</SelectRowTableProvider>
                      <Toaster />
                    </NextIntlClientProvider>
                  </MantineProvider>
                </ReactQueryConfig>
              </NuqsAdapter>
            </TokenProvider>
          </GoogleAuthProvider>
        </div>
      </body>
    </html>
  );
}
