const ROUTES = {
  HOME: "/",
  AUTH: {
    LOGIN: "/auth/login",
    SIGNUP: "/auth/signup",
    VERIFY_PHONE: "/auth/verify-phone",
    MAKE_HOME: "/auth/make-home",
    FORGOT_PASSWORD: "/auth/forgot-password",
    RESET_PASSWORD: "/auth/reset-password",
    CONFIRM: "/auth/confirm",
  },

  ADMIN: {
    DASHBOARD: "/admin",
    ACCOUNTS: "/admin/Accounts",
    ACCOUNTSDETAILS: (id) => `/admin/Accounts/${id}`,
    ACCOUNTSLISTDETAILS: (id) => `/admin/Accounts/list/${id}`,
    ACCOUNTSLISTDETAILSEDIT: (id) => `/admin/Accounts/list/${id}/edit`,
    NOTESACCOUNTS: "/admin/Accounts/Notes-History",
    NOTESACCOUNTSDETAILS: (id) => `/admin/Accounts/Notes-History/${id}`,
    LISTINGS: "/admin/Listings",
    LISTINGSADD: "/admin/Listings/add-list",
    LISTINGSDETAILS: (id) => `/admin/Listings/${id}`,
    LISTINGSDETAILSEdit: (id) => `/admin/Listings/${id}/edit`,
    SUPPORT: "/admin/Support",
    LESSORS: "/admin/Lessors",
    RENTERS: "/admin/Renters",
    BOOKINGS: "/admin/Bookings",
    NOTESBOOKINGS: "/admin/Bookings/Notes-History",
    NOTESBOOKINGSDETAILS: (id) => `/admin/Bookings/Notes-History/${id}`,
    BOOKINGSDETAILS: (id) => `/admin/Bookings/${id}`,
    INVOICES: "/admin/Invoices",
    RESERVATIONS: "/admin/Reservations",
    REPORTS: "/admin/Reports",
    MEMBERSHIPS: "/admin/Memberships",
    DEMOREQUEST: "/admin/demo-requests",
    INBOX: "/admin/Inbox",
    MASTERDATA: "/admin/master-data",
    PLANSADD: "/admin/master-data/add",
    CATEGORIES: "/admin/master-data/Categories",
    CATEGORIESID: (id) => `/admin/master-data/Categories/${id}`,
    CATEGORYADD: "/admin/master-data/Categories/add",
    BANNERS: "/admin/master-data/Banners",
    BANNERSADD: "/admin/master-data/Banners/add",
    ADS: "/admin/master-data/Ads",
    ADSPRICING: "/admin/master-data/Ads/ads-pricing",
    ADSDETAILS: (id) => `/admin/master-data/Ads/${id}`,
  },
  USER: {
    HOMEPAGE: "/user",
    DASHBOARD: "/user/Dashboard",
    CATEGORIES: (id) => `/user/Categories?category=${id}`,
    CATEGORIESPATH: `/user/Categories`,
    LISTINGS: "/user/Listings",
    LISTINGSDETAILS: (id) => `/user/Listings/${id}`,
    LISTINGSDETAILSADS: (id) => `/user/Listings/${id}/ads`,
    LISTINGSEDIT: (id) => `/user/Listings/${id}/edit`,
    RENTALS: "/user/Rentals",
    REQUESTS: "/user/Requests",
    BOOKINGS: "/user/Bookings",
    BOOKINGSID: (id) => `/user/Bookings/${id}`,
    ORDERID: (id) => `/user/Bookings/order/${id}`,
    INBOX: "/user/Inbox",
    CLIENTS: "/user/Clients",
    WISHLIST: "/user/Wishlist",
    CALENDAR: "/user/Calendar",
    BILLING: "/user/Billing",
    ADDLIST: "/user/add-list",
    PRODUCTDETAILS: (id) => `/user/product/${id}`,
    PRODUCTDETAILSCHECKOUT: (id) => `/user/product/${id}?checkout=true`,
    SUBSCRIPTION: "/user/subscription",
    CHECKOUT: "/user/checkout",
    CHECKOUTID: (id) => `/user/checkout/${id}`,
    PROFILE: "/user/profile",
    WALLET: "/user/Wallet",
    ADS: "/user/Ads",
    ADSID: (id) => `/user/Ads/${id}`,
    ADSDETAILSID: (id) => `/user/Ads/ads-details/${id}`,
    SUPPORT: "/user/Support",
    SUPPORTHISTORY: "/user/Support/support-history",
    SUPPORTFAQ: "/user/Support/Faq",
    SUPPORTCONTACT: "/user/Support/Contact",
    WAREHOUSES: "/user/Warehouses",
  },
  PREMIUM: {
    HOMEPAGE: "/premium",
    DASHBOARD: "/premium/Dashboard",
    CATEGORIES: (id) => `/premium/Categories?category=${id}`,
    CATEGORIESPATH: `/premium/Categories`,
    LISTINGS: "/premium/Listings",
    LISTINGSDETAILS: (id) => `/premium/Listings/${id}`,
    LISTINGSDETAILSADS: (id) => `/premium/Listings/${id}/ads`,
    LISTINGSEDIT: (id) => `/premium/Listings/${id}/edit`,
    CREATEORDER: "/premium/Listings/create-order",
    RENTALS: "/premium/Rentals",
    REQUESTS: "/premium/Requests",
    BOOKINGS: "/premium/Bookings",
    BOOKINGSID: (id) => `/premium/Bookings/${id}`,
    ORDERID: (id) => `/premium/Bookings/order/${id}`,
    INBOX: "/premium/Inbox",
    CLIENTS: "/premium/Clients",
    WISHLIST: "/premium/Wishlist",
    CALENDAR: "/premium/Calendar",
    BILLING: "/premium/Billing",
    ADDLIST: "/premium/add-list",
    PRODUCTDETAILS: (id) => `/premium/product/${id}`,
    PRODUCTDETAILSCHECKOUT: (id) => `/premium/product/${id}?checkout=true`,
    SUBSCRIPTION: "/premium/subscription",
    CHECKOUT: "/premium/checkout",
    CHECKOUTID: (id) => `/premium/checkout/${id}`,
    PROFILE: "/premium/profile",
    WALLET: "/premium/Wallet",
    ADS: "/premium/Ads",
    ADSID: (id) => `/premium/Ads/${id}`,
    ADSDETAILSID: (id) => `/premium/Ads/ads-details/${id}`,
    SUPPORT: "/premium/Support",
    SUPPORTHISTORY: "/premium/Support/support-history",
    SUPPORTFAQ: "/premium/Support/Faq",
    SUPPORTCONTACT: "/premium/Support/Contact",
    WAREHOUSES: "/premium/Warehouses",
    CLIENTS: "/premium/Clients",
    CLIENTSDETAILS: (id) => `/premium/Clients/${id}`,
    MAINTENANCE: "/premium/Maintenance",
    MAINTENANCEADD: "/premium/Maintenance/add",
    TAXES: "/premium/Taxes",
  },
  GUEST: {
    HOMEPAGE: "/",
    ALLPRODUCTS: `/Products`,
    PRODUCTS: (id) => `/Products?category=${id}`,
    PRODUCTSPATH: `/Products`,
    PRODUCTSDETAILS: (id) => `/Products/${id}`,
    PROFILE: (id, id2) => `/Products/${id}/profile/${id2}`,
    ADDLISTING: "Add-Listing",
    WHOWEARE: "/Who-We-Are",
    HOWITWORKS: "/How-It-Works",
    PRICING: "/Pricing",
    CONTACTUS: "/Contact-Us",
  },
};

export default ROUTES;
